apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: distributed-app
data:
  # settings route : payement/settings.py
  DJANGO_SETTINGS_MODULE: "payement.settings.base"

  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-payment"        # ← nom du Service postgres
  DB_NAME: "payement_db"
  DB_PORT: "5432"
  DB_USER: "payement_user"

  ALLOWED_HOSTS: "*"

  DEBUG: "False"