services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: pass_product
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Décommentez pour déboguer depuis votre machine
    # ports:
    #   - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - products_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker          # ← .env.docker comme tous les autres services
    environment:
      DB_HOST: postgres      # ← garanti vers le service postgres
      DJANGO_SETTINGS_MODULE: products.settings.base
    ports:
      - "8002:8000"          # ← 8002 : user=8001, payment=8004
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./products:/app/products
    networks:
      - products_network

networks:
  products_network:
    driver: bridge

volumes:
  postgres_data: