services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payement_db
      POSTGRES_USER: payement_user
      POSTGRES_PASSWORD: pass_payement
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Décommentez pour déboguer depuis votre machine
    # ports:
    #   - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payement_user -d payement_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - payment_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      DB_HOST: postgres                    # ← garanti vers le service postgres
      DJANGO_SETTINGS_MODULE: payement.settings.base
    ports:
      - "8004:8000"                        # ← user=8001, products=8002, orders=8003, payment=8004
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./payement:/app/payement
    networks:
      - payment_network

networks:
  payment_network:
    driver: bridge

volumes:
  postgres_data: