[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
pythonpath = .
django_find_project = false
python_files = tests/test_*.py tests/**/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
markers =
    unit: Tests unitaires
    integration: Tests d'intégration