upstream users_svc {
    server users:8000;
}

upstream products_svc {
    server products:8000;
}

upstream orders_svc {
    server orders:8000;
}

upstream payments_svc {
    server payments:8000;
}

upstream interation_svc {
    server interation:8000;
}

upstream frontend_svc {
    server frontend:3000;
}

server {
    listen 80;
    server_name localhost;

    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # ══════════════════════════════════
    #  Static files (admin + DRF CSS/JS)
    # ══════════════════════════════════
    location /static/ {
        proxy_pass http://users_svc/static/;
    }

    # ══════════════════════════════════
    #  API Microservices
    # ══════════════════════════════════
    location /api/users/ {
        proxy_pass http://users_svc/;
    }

    location /api/products/ {
        proxy_pass http://products_svc/;
    }

    location /api/orders/ {
        proxy_pass http://orders_svc/;
    }

    location /api/payments/ {
        proxy_pass http://payments_svc/;
    }

    location /api/interation/ {
        proxy_pass http://interation_svc/;
    }

    # ══════════════════════════════════
    #  Frontend React (catch-all)
    # ══════════════════════════════════
    location / {
        proxy_pass http://frontend_svc;
    }
}

# ══════════════════════════════════════════
#  Django Admin — un port par service
#
#  localhost:9001/admin/  → Users admin
#  localhost:9002/admin/  → Products admin
#  localhost:9003/admin/  → Orders admin
#  localhost:9004/admin/  → Payments admin
#  localhost:9005/admin/  → Interation admin
# ══════════════════════════════════════════

server {
    listen 9001;
    location / {
        proxy_pass http://users_svc;
        proxy_set_header Host $host;
    }
}

server {
    listen 9002;
    location / {
        proxy_pass http://products_svc;
        proxy_set_header Host $host;
    }
}

server {
    listen 9003;
    location / {
        proxy_pass http://orders_svc;
        proxy_set_header Host $host;
    }
}

server {
    listen 9004;
    location / {
        proxy_pass http://payments_svc;
        proxy_set_header Host $host;
    }
}

server {
    listen 9005;
    location / {
        proxy_pass http://interation_svc;
        proxy_set_header Host $host;
    }
}