apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: distributed-app
data:
  DJANGO_SETTINGS_MODULE: "orders.settings.base"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-orders"
  DB_NAME: "order_db"
  DB_PORT: "5432"
  DB_USER: "order_user"
  ALLOWED_HOSTS: "*"
  DEBUG: "False"