apiVersion: v1
apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: distributed-app
data:
  # settings route : orders/settings/base.py
  DJANGO_SETTINGS_MODULE: "orders.settings.base"

  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-orders"         # ← nom du Service postgres
  DB_NAME: "order_db"
  DB_PORT: "5432"
  DB_USER: "order_user"

  ALLOWED_HOSTS: "*"
  DEBUG: "False"