# Generated by Django 5.2.3 on 2026-04-04 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du mode de livraison (ex: Livraison standard)', max_length=100)),
                ('description', models.CharField(blank=True, help_text='3–5 jours ouvrés', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Prix de la livraison', max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cette option est disponible')),
                ('is_default', models.BooleanField(default=False, help_text='Définit cette option comme livraison par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='ID utilisateur provenant du auth-service', null=True)),
                ('session_id', models.UUIDField(blank=True, help_text='ID session pour les utilisateurs non connectés', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='orders_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(max_length=150)),
                ('product_image', models.URLField(blank=True)),
                ('product_size', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Prix unitaire figé au moment de la commande', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, help_text='Prix total par produit commander', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Somme des items, recalculée à chaque modification', max_digits=12)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, help_text='Frais de livraison', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pricings', to='orders_app.deliveryoption')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='orders_app.order')),
            ],
        ),
    ]
