# Generated by Django 5.2.3 on 2026-04-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
