# Generated by Django 6.0.3 on 2026-03-06 03:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du mode de livraison (ex: Livraison standard)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='3–5 jours ouvrés')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Prix de la livraison', max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cette option est disponible')),
                ('is_default', models.BooleanField(default=False, help_text='Définit cette option comme livraison par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pricings', to='orders_app.deliveryoption')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='orders_app.order')),
            ],
        ),
    ]
