# Generated by Django 6.0.3 on 2026-03-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_deliveryoption_orderpricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='description',
            field=models.CharField(blank=True, help_text='3–5 jours ouvrés', max_length=100),
        ),
    ]
