# Generated by Django 5.2.3 on 2026-04-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_alter_orderaddress_address_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpricing',
            name='currency',
            field=models.CharField(default='FCFA', max_length=10),
        ),
    ]
