# Generated by Django 6.0.3 on 2026-03-19 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Eau de Parfum', 'Eau de Parfum'), ('Eau de Toilette', 'Eau de Toilette'), ('Extrait de Parfum', 'Extrait de Parfum')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=20)),
                ('image', models.URLField()),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(choices=[('Floral', 'Floral'), ('Boisé', 'Boisé'), ('Oriental', 'Oriental'), ('Fruité', 'Fruité'), ('Aromatique', 'Aromatique')], max_length=50)),
                ('gender', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Unisexe', 'Unisexe')], max_length=20)),
                ('notes_top', models.TextField(blank=True, help_text='Notes de tête (ex: Bergamote, Citron)')),
                ('notes_heart', models.TextField(blank=True, help_text="Notes de cœur (ex: Jasmin, Fleur d'oranger)")),
                ('notes_base', models.TextField(blank=True, help_text='Notes de fond (ex: Musc blanc, Santal)')),
                ('composition', models.TextField(blank=True, help_text='Liste des ingrédients')),
                ('advice', models.TextField(blank=True, help_text="Conseils d'application et précautions")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
