apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-products-pvc
  namespace: distributed-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-products
  namespace: distributed-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-products
  template:
    metadata:
      labels:
        app: postgres-products
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_DB
              value: "product_db"
            - name: POSTGRES_USER
              value: "product_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: products-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "product_user", "-d", "product_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "product_user"]
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-products-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-products
  namespace: distributed-app
spec:
  selector:
    app: postgres-products
  ports:
    - port: 5432
      targetPort: 5432