apiVersion: v1
kind: ConfigMap
metadata:
  name: interation-config
  namespace: distributed-app
data:
  DJANGO_SETTINGS_MODULE: "interation.settings.base"
  DB_ENGINE: "django.db.backends.postgresql"
  DB_HOST: "postgres-interation"
  DB_NAME: "interation_db"
  DB_PORT: "5432"
  DB_USER: "interation_user"
  ALLOWED_HOSTS: "*"
  DEBUG: "False"