services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: capedev/api-gateway:latest
    container_name: gateway
    restart: always
    ports:
      - "80:80"
      - "9001:9001"
      - "9002:9002"
      - "9003:9003"
      - "9004:9004"
      - "9005:9005"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - microservices-net

networks:
  microservices-net:
    name: microservices-net
    driver: bridge